
CREATE TABLE IF NOT EXISTS ideas (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  idea TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ideas_id_idx ON ideas(id);

CREATE TRIGGER IF NOT EXISTS update_ideas_updated_at
AFTER UPDATE ON ideas
FOR EACH ROW
BEGIN
  UPDATE ideas SET updated_at = CURRENT_TIMESTAMP WHERE id = OLD.id;
END;

